### ISSUE TITLE
Question about Generator Loss

### ISSUE THREAD

**Issue by Akamight** [kam1107/RealnessGAN#1]
In the arxiv preprint version of the paper, it is explicitly stated that most of the results used Eq. 19, D_{KL}(D(x) || D(G(z))) - D_{KL}(A_0||D(G(z))).

However, in the learnG.py implementation, the actual loss used is D_{KL}(D(x) || D(G(z))) only.
`if param.relativisticG:
lossG = Triplet_Loss(feat_real, feat_fake)`

Why is that?

**Comment by kam1107** [comment]
Hi, thanks for noticing :) It was a mistake and I just fixed it. Sorry for the confusion.

**Comment by BridgetteSong** [comment]
a small question about Generator loss, in the code:
lossG = -Triplet_Loss(anchor_fake, feat_fake, skewness=param.negative_skew) + Triplet_Loss(feat_real, feat_fake)
this loss can be always positive? Could it be negative in some times?

**Comment by kam1107** [comment]
Yes it can negative.
