### ISSUE TITLE
Supplementary Material

### ISSUE THREAD

**Issue by rrmina** [kam1107/RealnessGAN#2]
Hi there. Thanks for doing good research and for sharing your codes. 

Do you perhaps have a separate supplementary material for your paper? 

Thank you very much.

**Comment by kam1107** [comment]
Hi, exactly what kind of material are you looking for?

**Comment by rrmina** [comment]
I am thinking of a material that includes the exact network architecture used in the experiments (for each dataset), as well as the hyperparameters in training. Similar to this https://cs.stanford.edu/people/jcjohns/papers/fast-style/fast-style-supp.pdf

**Comment by kam1107** [comment]
Thank your for pointing out. We used the same architecture as the original work, e.g. DCGAN and StyleGAN, as well as the hyperparameters, just extended them with realness distribution. If you need detailed information please refer to the original paper. The settings are also briefly mentioned in Sec.4 in our paper.
