### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Tianshuo-Xu** [kam1107/RealnessGAN#3]
Thanks for your Amazing work! It helps me a lot. But when I firstly use it, I got Error like: "RNN.utills not in model", and I change the name of folder: "model" to others, it work! So I suggest, maybe you can change the name of "model" folder in new release.

**Comment by kam1107** [comment]
Hi, thank you for your appreciation :)  However, I did not come across this issue on my computer. I will double check it just to ensure.
