### ISSUE TITLE
Can you release your model ?

### ISSUE THREAD

**Issue by DavieHR** [kam1107/RealnessGAN#4]
THX

**Comment by kam1107** [comment]
Hi, sorry for replying late. RealnessGAN is not difficult to train especially on small dataset. You can try to train one on your own and adjust parameters according to your requirement. However, I can provide pretrained model on FFHQ dataset for reference if that's what you are looking for: https://drive.google.com/file/d/1NapKYf90NMQwk0TNTuMIb22RN3OeC0PU/view?usp=sharing
