### ISSUE TITLE
Feature resampling

### ISSUE THREAD

**Issue by TropComplique** [kam1107/RealnessGAN#5]
Hi. I like your paper a lot.

There is no feature resampling like in the paper in this code.
Do you use "re-parameterization trick" [here](https://github.com/kam1107/RealnessGAN/blob/master/model/DCGAN_model.py#L92) as an alternative?

**Comment by kam1107** [comment]
Thank you for noticing and yes they are the same. I will update the comment. Sorry for the confusion.
