### ISSUE TITLE
Configs for cifar10 training?

### ISSUE THREAD

**Issue by naoto0804** [kam1107/RealnessGAN#7]
Thank for releasing nice work!

I want to reproduce your cifar10 experiment as the baseline for my research.
I copy `scripts/run_CelebA.sh` and create `scripts/run_cifar10.sh`, and modify some parameters `--CIFAR10 True` and `--num_outcomes 3` (based on p6 of your paper).  Is there any parameter that I should change in addition, or is it possible to provide the exact script?

**Comment by kam1107** [comment]
Hi, sorry for replying late. Apart from num_outcomes you can also try to increase the update frequency of G e.g. G_updates=3

**Comment by kam1107** [comment]
In case you need a pre-trained model, here's the link: https://drive.google.com/file/d/1FmO6JYTTtYLW38b-dfW_HDrqXzlm1yrF/view?usp=sharing
We turned off re-sampling trick and use  G_updates=3 in this case.

**Comment by naoto0804** [comment]
Thanks a lot! Do you use `--total_iters 520000` even for the cifar10 experiment?

**Comment by kam1107** [comment]
We set it to 520000 to inspect mode collapse but it doesn't need this many rounds to converge.
